# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fH2_PW_HcQ2_ErGJm7cpb_FE5214yYbA
"""

import streamlit as st
import torch
import torch.nn as nn
import librosa
import librosa.display
import numpy as np
import os
import tempfile
import matplotlib.pyplot as plt

# --- PAGE LAYOUT & PROJECT CONFIGURATION ---
st.set_page_config(
    page_title="Deepfake Audio Detector",
    page_icon="🎙️",
    layout="centered"
)

st.title("Deepfake Audio Detection")
st.markdown("---")

TARGET_SR = 16000
MAX_DURATION = 4 # seconds
MEL_BINS = 128

# --- MODEL ARCHITECTURE ---
class DeepfakeAudioDetectorCNN(nn.Module):
    def __init__(self):
        super(DeepfakeAudioDetectorCNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 16, kernel_size=3, stride=1, padding=1)
        self.relu1 = nn.ReLU()
        self.pool1 = nn.MaxPool2d(kernel_size=2, stride=2)

        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1)
        self.relu2 = nn.ReLU()
        self.pool2 = nn.MaxPool2d(kernel_size=2, stride=2)

        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.relu3 = nn.ReLU()
        self.pool3 = nn.MaxPool2d(kernel_size=2, stride=2)

        self.adaptive_pool = nn.AdaptiveAvgPool2d((4, 4))
        self.fc1 = nn.Linear(64 * 4 * 4, 128)
        self.dropout = nn.Dropout(0.5)
        self.fc2 = nn.Linear(128, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.pool1(self.relu1(self.conv1(x)))
        x = self.pool2(self.relu2(self.conv2(x)))
        x = self.pool3(self.relu3(self.conv3(x)))
        x = self.adaptive_pool(x)
        x = x.view(x.size(0), -1)
        x = self.dropout(self.fc1(x))
        x = self.sigmoid(self.fc2(x))
        return x

# --- FEATURE EXTRACTION PIPELINE ---
def compute_melspectrogram(audio_path):
    try:
        waveform, sr = librosa.load(audio_path, sr=TARGET_SR, duration=MAX_DURATION)
        if len(waveform) < TARGET_SR * MAX_DURATION:
            waveform = np.pad(waveform, (0, TARGET_SR * MAX_DURATION - len(waveform)))
        mel_features = librosa.feature.melspectrogram(y=waveform, sr=sr, n_mels=MEL_BINS)
        return librosa.power_to_db(mel_features, ref=np.max)
    except Exception as e:
        st.error(f"Error processing {audio_path}: {e}")
        return None

# --- CACHED MODEL WEIGHT LOADER ---
@st.cache_resource
def load_deepfake_model():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model_filename = "deepfake_audio_model.pth"

    if not os.path.exists(model_filename):
        return None, f"Weights file '{model_filename}' missing from workspace repository."

    try:
        model = DeepfakeAudioDetectorCNN().to(device)
        model.load_state_dict(torch.load(model_filename, map_location=device))
        model.eval()
        return model, device
    except Exception as e:
        return None, str(e)

# Initialize Model
model, context_err = load_deepfake_model()

# --- USER INTERFACE & INFERENCE LOOP ---
if model is None:
    st.error(f"🚨 Initialization Error: {context_err}")
else:
    # Audio File Input Target
    uploaded_file = st.file_uploader(
        "Upload audio recording sample for validation:",
        type=["wav", "mp3", "ogg", "flac"]
    )

    if uploaded_file is not None:
        st.write("---")
        st.subheader("Analysis & Playback Pipeline")

        # Audio playback element
        st.audio(uploaded_file)

        # Write bytes safely to temporary disk for librosa utility actions
        with tempfile.NamedTemporaryFile(delete=False, suffix=os.path.splitext(uploaded_file.name)[1]) as tmp_file:
            tmp_file.write(uploaded_file.read())
            tmp_filepath = tmp_file.name

        try:
            # Execute your exact training feature extractor
            extracted_features = compute_melspectrogram(tmp_filepath)

            # Replicate custom dataset fallback padding logic
            if extracted_features is None:
                extracted_features = np.zeros((MEL_BINS, int(TARGET_SR * MAX_DURATION / 512)))

            # Plot visual log-mel spectrogram for project demonstration video
            fig, ax = plt.subplots(figsize=(10, 3.5))
            img = librosa.display.specshow(extracted_features, sr=TARGET_SR, x_axis='time', y_axis='mel', ax=ax, cmap='magma')
            fig.colorbar(img, ax=ax, format='%+2.0f dB')
            ax.set_title("Extracted Log-Mel Spectrogram")
            st.pyplot(fig)

            # Format features into model batch configuration tensor [Batch=1, Channel=1, Mel, Time]
            feature_tensor = torch.tensor(extracted_features, dtype=torch.float32).unsqueeze(0).unsqueeze(0)
            device = next(model.parameters()).device
            feature_tensor = feature_tensor.to(device)

            # Pass tensor data through network forward paths
            with torch.no_grad():
                output = model(feature_tensor).squeeze()
                prob = output.item() if output.ndim == 0 else output[0].item()

            # Process prediction probabilities into mandatory target string verdicts
            if prob > 0.5:
                verdict = "Deepfake (AI-Generated)"
                confidence = prob * 100
                st.error(f"⚠️ **Prediction Result:** {verdict}")
            else:
                verdict = "Genuine (Human)"
                confidence = (1 - prob) * 100
                st.success(f"✅ **Prediction Result:** {verdict}")

            # Display required confidence metric value card
            st.metric(label="Identification Confidence Score", value=f"{confidence:.2f}%")

        except Exception as e:
            st.error(f"Failed pipeline execution. Details: {e}")
        finally:
            # File system cleanup
            if os.path.exists(tmp_filepath):
                os.remove(tmp_filepath)