# -*- coding: utf-8 -*-
"""testing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s1PzsutZoPSndbm__xd-hoHN9mYbY7LL
"""

import os
import sys
import torch
import torch.nn as nn
import librosa
import numpy as np

# --- MODEL ARCHITECTURE ---
class DeepfakeAudioDetectorCNN(nn.Module):
    def __init__(self):
        super(DeepfakeAudioDetectorCNN, self).__init__()

        # Block 1: Basic edge & frequency detection (16 channels)
        self.conv1 = nn.Conv2d(1, 16, kernel_size=3, stride=1, padding=1)
        self.bn1 = nn.BatchNorm2d(16)
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.relu = nn.ReLU()

        # Block 2: Intermediate patterns (32 channels)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1)
        self.bn2 = nn.BatchNorm2d(32)

        # Block 3: High-level audio features (64 channels)
        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)
        self.bn3 = nn.BatchNorm2d(64)

        # Global Average Pooling (GAP) to prevent spatial memorization
        self.gap = nn.AdaptiveAvgPool2d((1, 1))

        # Minimal Classifier Head
        self.dropout = nn.Dropout(0.3)
        self.fc = nn.Linear(64, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        x = self.pool(self.relu(self.bn1(self.conv1(x))))
        x = self.pool(self.relu(self.bn2(self.conv2(x))))
        x = self.pool(self.relu(self.bn3(self.conv3(x))))

        x = self.gap(x)
        x = x.view(x.size(0), -1) # Flattens to [batch_size, 64]

        x = self.dropout(x)
        x = self.sigmoid(self.fc(x))
        return x

# --- PREPROCESSING PIPELINE ---
TARGET_SR = 16000
MAX_DURATION = 4 # seconds
MEL_BINS = 128

def compute_melspectrogram(audio_path):
    try:
        waveform, sr = librosa.load(audio_path, sr=TARGET_SR, duration=MAX_DURATION)
        if len(waveform) < TARGET_SR * MAX_DURATION:
            waveform = np.pad(waveform, (0, TARGET_SR * MAX_DURATION - len(waveform)))
        mel_features = librosa.feature.melspectrogram(y=waveform, sr=sr, n_mels=MEL_BINS)
        return librosa.power_to_db(mel_features, ref=np.max)
    except Exception as e:
        print(f"Error processing {audio_path}: {e}")
        return None

# --- SINGLE FILE INFERENCE PIPELINE ---
def predict_audio(file_path, model, device):
    feature_tensor = compute_melspectrogram(file_path)
    if feature_tensor is None:
        return

    # --- THE FIX HAPPENS HERE ---
    # 1. Convert NumPy array to a PyTorch Tensor and ensure it's a Float
    feature_tensor = torch.from_numpy(feature_tensor).float()

    # 2. Add Batch and Channel dimensions: (H, W) -> (1, 1, H, W)
    feature_tensor = feature_tensor.unsqueeze(0).unsqueeze(0)

    # 3. Safely move the prepared tensor to your device
    feature_tensor = feature_tensor.to(device)
    # ----------------------------

    model.eval()

    with torch.no_grad():
        output = model(feature_tensor).squeeze()
        prob = output.item() if output.ndim == 0 else output[0].item()

    # Interpret Sigmoid outputs (0 = Genuine, 1 = Deepfake)
    if prob > 0.5:
        label = "Deepfake (AI-Generated)"
        confidence = prob * 100
    else:
        label = "Genuine (Human)"
        confidence = (1 - prob) * 100

    print("\n" + "="*45)
    print("           AUDIO INFERENCE REPORT           ")
    print("="*45)
    print(f" File Target : {os.path.basename(file_path)}")
    print(f" Prediction  : {label}")
    print(f" Confidence  : {confidence:.2f}%")
    print("="*45 + "\n")

# --- EXECUTION CONTROLLER ---
if __name__ == "__main__":
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model_filename = "deepfake_audio_model.pth"

    if not os.path.exists(model_filename):
        print(f"[ERROR] Weights file '{model_filename}' not found in this directory.")
        print("Please place this script in the same folder as your '.pth' file.")
        sys.exit(1)

    try:
        model = DeepfakeAudioDetectorCNN().to(device)
        model.load_state_dict(torch.load(model_filename, map_location=device))
        print(f"--> Model successfully loaded on: {device}")

        audio_file = input("\nEnter the path to your test audio file: ").strip()

        audio_file = audio_file.strip("'\"")

        # Validate and execute prediction
        if os.path.exists(audio_file):
            predict_audio(audio_file, model, device)
        else:
            print(f"[ERROR] File '{audio_file}' does not exist. Please check the path and try again.")

    except Exception as e:
        print(f"\n[ERROR] Pipeline failure. Details: {e}")